name: blacksmithvfx-environment
channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
- git:
  - https://bitbucket.org/ftrack/ftrack-connect.git@64b062c0b6b86ba45225878f154f0e04180cbfe1
  - https://bitbucket.org/tokejepsen/ftrack-connect-maya.git@4487fa733768a90d3a831d4570a8606c4a3d1556
  - https://github.com/tokejepsen/ftrack-hooks.git@5936f77465687cd4b4d86ecc4a331ae8abab5782
  - https://github.com/tokejepsen/ftrack-template.git@42f5e40cd634fb8a50998afaedc4f2cea229139b
  - https://github.com/pyblish/pyblish-base.git@6dc5781d6bb7b97fb7bc9df268f59e24a477c272
  - https://github.com/tokejepsen/pyblish-blacksmithvfx.git@fc6d1c22b74578e55b439f9dc6575315bdae92cc
  - https://github.com/bumpybox/pyblish-bumpybox.git@01563e062f9c477b339f8270c23984e20715a18c
  - https://github.com/tokejepsen/pyblish-deadline.git@80c1d5b3d3bed044445a473caa6a9a227a956395
  - https://github.com/tokejepsen/pyblish-ftrack.git@f9d5c7b02607ed86ded0532136b4c743581534bf
  - https://github.com/pyblish/pyblish-houdini.git@88b189a82fd6b757aa7557c1c490b97e740154a5
  - https://github.com/tokejepsen/pyblish-lite.git@543a64d4d6f6d6ce425a52b9eba8969b8e896366
  - https://github.com/pyblish/pyblish-maya.git@93651557bb62d3f367d3ec753b7b832398373888
  - https://github.com/tokejepsen/blacksmithvfx-environment.git:
    - python $REPO_PATH/environment.py
  - https://github.com/bumpybox/bumpybox-environment.git@542fd14ee14efc44bd8a1d167fa7a42c1e8f1cc6:
    - python $REPO_PATH/startup.py
