channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
  - arrow
  - riffle
- git:
  - https://bitbucket.org/ftrack/ftrack-connect.git@64b062c0b6b86ba45225878f154f0e04180cbfe1
  - https://bitbucket.org/tokejepsen/ftrack-connect-maya.git@a3357544ab4986f7fcab45b05b74e669d987ea1f
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git@4a5323c453855ff909b7ba6b7ce8ac43617977a2
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git@51dfcb367c0531b413de85f6d77fabb0be90b009
  - https://bitbucket.org/ftrack/ftrack-connect-nuke-studio.git@dc5e0f3d1b971ea1e95c41a78af69a26dc68ef3a
  - https://bitbucket.org/ftrack/ftrack-connect-rv.git@2afb77536bbc2b89f987c8e0311fb63ed3d5fe32
  - https://github.com/tokejepsen/ftrack-hooks.git@ebe7a9b02101ef3aa8c85f2da87b878cfb0cf763
  - https://github.com/tokejepsen/ftrack-locations.git@daa5a868b2cfd25ef49b685b328d11c72d5da2e2
  - https://github.com/tokejepsen/ftrack-template.git@825e29b1a81a65a38fc56f4e5b744b23a79e72df
  - https://github.com/pyblish/pyblish-base.git@9a3d78772f73e5905c131f9431cc3a266b23cbf7
  - https://github.com/pyblish/pyblish-standalone.git@0f279c0e08f4c99bd6e5ef954452835e01e2ee61
  - https://github.com/bumpybox/pyblish-bumpybox.git@156fcde5eb333f4495e18e9e0d3004f5af147b14
  - https://github.com/pyblish/pyblish-deadline.git@10c1a4ff3fd4f44dc7ff34f104fa41a62adb3091
  - https://github.com/pyblish/pyblish-ftrack.git@8a28b879e7bbcfc989c178fa1d8c0671c7ac6a8d
  - https://github.com/pyblish/pyblish-houdini.git@88b189a82fd6b757aa7557c1c490b97e740154a5
  - https://github.com/pyblish/pyblish-lite.git@5c9bd64bc649a1537f79682866a37258639b66a0
  - https://github.com/pyblish/pyblish-maya.git@b81e6edd67e9969348a133c8a6e630ab92fd6c3f
  - https://github.com/pyblish/pyblish-nuke.git@5ec2594cd9d987dfdb10abee59ab3044d4a08225
  - https://github.com/tokejepsen/ftrack-connect-environment.git@777a260885fda1ce9076c7f2714ae309bdaae00c:
    - python $REPO_PATH/environment.py
  - https://github.com/blacksmithvfx/blacksmithvfx-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
name: blacksmithvfx-environment
